Add support for a TextPacket, as sent using the UART module in the Ad…
adafruit/Adafruit_CircuitPython_BluefruitConnect pull request #33
Opened 2021-11-30 19:02 UTC by TonyLHansen

Add support for a TextPacket, as sent using the UART module in the AdaFruit BlueTooth app

This code provides an exception case to the Packet creation logic, similar to how the sample Arduino BLE code for the LED Glasses also has an exception case when the UART stream has data that does not start with a "!".

2021-12-12 15:05 UTC, FoamyGuy requested changes
Thanks for adding this feature @TonyLHansen! The changes to the library look good to me, and I was able to test them successfully with modified simpletest on:
```
Adafruit CircuitPython 7.1.0-beta.2 on 2021-12-10; Adafruit Circuit Playground Bluefruit with nRF52840
Board ID:circuitplayground_bluefruit
```
One request though if you are up for it: I think it would be great to include an example of using the new TextPacket type.

For testing I added this to the main loop inside of the simpletest script in the examples directory:
```py
        if isinstance(packet, TextPacket):
            print("Received Text Packet:")
            print(packet.text)
```
I think we should either add that to the simpletest in the repo, or add a new example script that shows the TextPacket usage. This will make it easier for folks to find this new feature and see how to use it.

2021-12-13 14:19 UTC, TonyLHansen commented
@FoamyGuy, I decided to add a separate simpletest2.py example.

2021-12-13 16:29 UTC, dhalbert requested changes
I'm confused. The Bluefruit Connect app UART page does not send text packets with any kind of header. It simply sends raw text characters. (It has been a misconception in the past that it sent a particular packet type.) So there is no "text packet" type. But maybe I'm missing something.

2021-12-13 16:36 UTC, dhalbert commented
OK, I see that if you find unknown characters, you turn it into a `TextPacket`. One reason for not doing this in the past is that if you get out of sync, and miss a beginning "!" in another packet, then you'll read text as a `TextPacket` indefinitely until the data happens to have a byte that is a newline.

2021-12-13 18:55 UTC, TonyLHansen commented
You are correct that it is possible for the packets to get out of sync if characters are missed. 

However:

- That is a true statement if characters are missed for _any_ of the packet types.
- Without code similar to this, the circuit python client code has to jump through hoops to get at the text data.
- This class addition is still done in same way as the other packets, such that, if you don't want the XYZPackets, you don't import the class.
- This class addition makes the circuit python client code easy to write.

Possibly most important from my point of view:

- The arduino version of the "scrolling text" code does almost the exact same thing as this code is doing. That's where I got the ideas on how to handle the UART text.
- It works with the current app just fine.

I don't disagree with your statement that updating the app to have a real "send text" capability would be useful. However I think that approach can be dealt with separately, and shouldn't prevent changes that work with the current version of the app.

2021-12-13 21:56 UTC, dhalbert commented
@TonyLHansen Thanks for the reply. I was missing the context of this change - I apologize if I seemed critical. Other people have asked for text packet functionality in the past, and were expecting a "!"-type packet.

How about we call this `RawTextPacket` or `TextRawPacket`, to distinguish its unusual data handling? If a regular text packet is added in the future, we can add a `TextPacket` class that does the usual header processing.

I would be fine with this PR after that.

2021-12-13 23:45 UTC, dhalbert approved these changes
Thanks for your patience!

2021-12-13 23:52 UTC, merged